name: pyvhr
channels:
  - pytorch
  - rapidsai
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - anaconda_prompt=1.1.0=haa95532_0
  - anyio=4.6.2=py39haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py39haa95532_0
  - attrs=24.3.0=py39haa95532_0
  - babel=2.11.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py39haa95532_0
  - brotli-python=1.0.9=py39hd77b12b_8
  - ca-certificates=2025.2.25=haa95532_0
  - certifi=2025.1.31=py39haa95532_0
  - cffi=1.17.1=py39h827c3e9_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - cuda-version=11.3=hbc958af_3
  - cudatoolkit=11.3.1=hf2f0253_13
  - cupy=13.3.0=py39h3739db2_2
  - cupy-core=13.3.0=py39hd00a30a_2
  - cusignal=23.08.00=py39_230809_g42d12fd_0
  - debugpy=1.6.7=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fastrlock=0.8.3=py39hf1781b0_1
  - freetype=2.12.1=ha860e81_0
  - h11=0.14.0=py39haa95532_0
  - hdf5=1.10.6=h1756f20_1
  - httpcore=1.0.2=py39haa95532_0
  - httpx=0.27.0=py39haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py39haa95532_0
  - ipython=8.15.0=py39haa95532_0
  - ipywidgets=8.1.5=py39haa95532_0
  - jedi=0.19.2=py39haa95532_0
  - jinja2=3.1.4=py39haa95532_1
  - jpeg=9b=hb83a4c4_2
  - json5=0.9.25=py39haa95532_0
  - jsonschema=4.23.0=py39haa95532_0
  - jsonschema-specifications=2023.7.1=py39haa95532_0
  - jupyter-lsp=2.2.0=py39haa95532_0
  - jupyter_client=8.6.0=py39haa95532_0
  - jupyter_core=5.7.2=py39haa95532_0
  - jupyter_events=0.10.0=py39haa95532_0
  - jupyter_server=2.14.1=py39haa95532_0
  - jupyter_server_terminals=0.4.4=py39haa95532_1
  - jupyterlab=4.2.5=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py39haa95532_0
  - jupyterlab_widgets=3.0.13=py39haa95532_0
  - lcms2=2.12=h83e58a3_0
  - lerc=4.0.0=h5da7b33_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=8_h719fc58_netlib
  - libdeflate=1.22=h5bf469e_0
  - liblapack=3.9.0=8_h719fc58_netlib
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - llvmlite=0.43.0=py39hf2fb9eb_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-inline=0.1.6=py39haa95532_0
  - mistune=2.0.4=py39haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.8.0=py39haa95532_0
  - nbconvert=7.16.4=py39haa95532_0
  - nbformat=5.10.4=py39haa95532_0
  - nest-asyncio=1.6.0=py39haa95532_0
  - ninja=1.12.1=haa95532_0
  - ninja-base=1.12.1=h4157e71_0
  - notebook=7.2.2=py39haa95532_1
  - notebook-shim=0.2.3=py39haa95532_0
  - numba=0.60.0=py39h5dcb127_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.4.0=h2466b09_0
  - overrides=7.4.0=py39haa95532_0
  - packaging=24.2=py39haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py39haa95532_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.3.1=pyhd8ed1ab_0
  - platformdirs=3.10.0=py39haa95532_0
  - powershell_shortcut=0.0.1=haa95532_4
  - prometheus_client=0.21.0=py39haa95532_0
  - prompt-toolkit=3.0.43=py39haa95532_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-fastjsonschema=2.20.0=py39haa95532_0
  - python-json-logger=3.2.1=py39haa95532_0
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - pywin32=305=py39h2bbff1b_0
  - pywinpty=2.0.14=py39h72d21ff_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - pyzmq=26.2.0=py39h5da7b33_0
  - referencing=0.30.2=py39haa95532_0
  - requests=2.32.3=py39haa95532_1
  - rfc3339-validator=0.1.4=py39haa95532_0
  - rfc3986-validator=0.1.1=py39haa95532_0
  - rpds-py=0.10.6=py39h636fa0f_1
  - scipy=1.13.1=py39h1a10956_0
  - send2trash=1.8.2=py39haa95532_0
  - setuptools=75.1.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py39haa95532_0
  - soupsieve=2.5=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py39haa95532_0
  - tinycss2=1.2.1=py39haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tomli=2.0.1=py39haa95532_0
  - tornado=6.4.2=py39h827c3e9_0
  - traitlets=5.14.3=py39haa95532_0
  - typing-extensions=4.12.2=py39haa95532_0
  - typing_extensions=4.12.2=py39haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - websocket-client=1.8.0=py39haa95532_0
  - wheel=0.44.0=py39haa95532_0
  - widgetsnbextension=4.0.13=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - absl-py==2.1.0
      - antropy==0.1.9
      - asteval==1.0.5
      - astunparse==1.6.3
      - autorank==1.2.1
      - baycomp==1.0.3
      - blinker==1.9.0
      - catboost==1.2.7
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dill==0.3.9
      - flask==3.1.0
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - future==1.0.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - idna==3.10
      - imageio==2.36.1
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - joblib==1.4.2
      - kaleido==0.2.1
      - keras==3.7.0
      - keras-tuner==1.4.7
      - kiwisolver==1.4.7
      - kt-legacy==1.0.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightgbm==4.6.0
      - lmfit==1.3.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mediapipe==0.10.20
      - ml-dtypes==0.4.1
      - mlxtend==0.23.4
      - namex==0.0.8
      - networkx==3.2.1
      - nolds==0.6.1
      - numpy==1.26.4
      - opencv-contrib-python==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.13.1
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.0.0
      - plotly==5.24.1
      - protobuf==4.25.5
      - pyasn1==0.6.1
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pysimplegui==5.0.7
      - python-graphviz==0.20.3
      - pytz==2024.2
      - pyvhr==2.0
      - pywavelets==1.6.0
      - rich==13.9.4
      - rsa==4.9
      - scikit-image==0.24.0
      - scikit-learn==1.6.0
      - scikit-posthocs==0.11.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shap==0.47.1
      - shortuuid==1.0.13
      - sklearn==0.0
      - slicer==0.0.8
      - sounddevice==0.5.1
      - statsmodels==0.14.4
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-intel==2.18.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - torch==1.9.1
      - torchaudio==0.10.0+cu113
      - torchvision==0.11.1+cu113
      - tqdm==4.67.1
      - tzdata==2024.2
      - uncertainties==3.2.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - xgboost==2.1.4
prefix: C:\Users\Ask\.conda\envs\pyvhr
